export * from './asset-items.route';
// export * from './asset-movement.route';
export * from './asset-request.route';
export * from './asset-route';
export * from './asset-type.route';
export * from './auth.route';
export * from './location.route';
export * from './rack-cupboard.route';
export * from './row.route';
export * from './user.route';
